### ISSUE TITLE
Packaging: Confusion about upstream info

### ISSUE THREAD

**Issue by ayekat** [rocasa/ttylog#10]
I have user-packaged [ttylog for Arch Linux][aur:ttylog], but it's not very clear to me what should be considered the "official" upstream site: there is a [sourceforge website][url:sf] (citing 0.26 as last release), a [sourceforge code repository][url:sfrepo], this git repo, and a [github.io website][url:ghio].

Which one is considered "official"?

[aur:ttylog]: https://aur.archlinux.org/packages/ttylog/
[url:sf]: http://ttylog.sourceforge.net/
[url:sfrepo]: https://sourceforge.net/projects/ttylog/
[url:ghio]: http://git.rocasa.org/

**Comment by jame** [comment]
The original one is the one at SourceForge, with the one here intended to be a mirror of that one.  The order in which they get updated may change from time to time, especially if a Pull Request here is used. There may be delays with getting the websites updated, either there or here.

**Comment by ayekat** [comment]
OK.

Thank you for the reply!
