### ISSUE TITLE
Get constantly repeating message 'vboxnetctl'

### ISSUE THREAD

**Issue by fedulovivan** [rocasa/ttylog#2]
Installed on osx with brew 
`bash-3.2$ brew install ttylog`
Trying to redirect serial device data to file
`bash-3.2$ ttylog -b 115200 -d /dev/cu.wchusbserial1410 -f > test.txt`
Get the following data in test file (head also shows binary file warning):

```
bash-3.2$ head -n 20 test.txt
stdin
stdout
stderr
�
I
afsc_type5
io8logtemp
vboxnetctl
vboxnetctl
vboxnetctl
...
```

Btw, screen command produces expected results:

```
bash-3.2$ screen /dev/cu.wchusbserial1410 115200
20/4/2016 01:48:58;6.00;94
20/4/2016 01:48:58;6.00;94
```

**Comment by jame** [comment]
Some questions:
- Which version of ttylog was this?
- Which version of OS/X was this?  And how was it being run? (*vboxnetctl* appears to be related to virtualbox)
- What was */dev/cu.wchusbserial1410* ?

**Comment by fedulovivan** [comment]
I tried that with ttylog version 0.25, OSX 10.10.5 right on MBP, without any virtualisation. cu.wchusbserial1410 is Chinese usr > serial adapter.

**Comment by jame** [comment]
Ah, I see what was at least an aspect of the problem you've been seeing:  there was an issue with the v0.25 version of *ttylog* where the modem_device string was being truncated.  That was corrected in version v0.26, which was released in June of 2015.  I would have thought that newer version would have been picked up by brew...  Please try the newer version if you have not already done so and let me know how it goes.

**Comment by jame** [comment]
Note that the release archive is available at https://sourceforge.net/projects/ttylog/files/ttylog/0.26/.

**Comment by jame** [comment]
Since there was no further followup from him, assuming that the issue was resolved.
